### ISSUE TITLE
The PDF shows country of vaccination, instead of country of issuance for the EU Flag with the 2 digit Country Code

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-issuance-web#109]
The PDF Generated on the 1st page shows the EU Flag, with the 2 Digit Country which the Vaccination was administered.
The PDF front page is supposed to show which country issued the certificate, and not which country administered the vaccination.

The bug exists in this line:
https://github.com/eu-digital-green-certificates/dgca-issuance-web/blob/c8fe6bf4e98d17de869f354ace2ba3301bb38767/src/misc/usePdfGenerator.tsx#L401

The field should display the Country of Issuance, and not the Country of Vaccinate Administration.

Please see the usage of the field here:
https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#country-code-and-issuer

**Comment by kerstin-oppermann-tsi** [comment]
retested with issuance web 5/11/2021
