### ISSUE TITLE
Field "birth day" (required field) is not checked

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-issuance-web#154]
## Describe the bug
the filed "date of birth" is a requiered filed( marked with a "*")  can be leaved
empty and a qr-code can be created
this fits all three certificate types (VAC, TEST, REC)

## Expected behaviour
its not allowd to leave this field empty

## Technical details
- Linux Fedora 34
- Chrome browser

## Additional context

![issue-web-page](https://user-images.githubusercontent.com/97519435/153175525-e35990f2-4653-41b3-bd5d-b24c04f5c1dc.png)

**Comment by fOppenheimer** [comment]
Fixed: Set date of birth to required.

**Comment by michawol** [comment]
its already deployed? It's still possible to leave date of birth field empty

**Comment by kerstin-oppermann-tsi** [comment]
Was deployed yesterday evening. Now it works. You can check @michawol

**Comment by Ren9111** [comment]
You have create a GP?

**Comment by michawol** [comment]
is fixed. Thanks.
