### ISSUE TITLE
All Certificates are Valid for 1 year when generated using the dgca-issuance-web

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-issuance-web#81]
The QR Code must have a Certificate Valid from and Valid to date set appropriately.
Currently, all QR Codes are valid for exactly 1 Year, which is not correct.

For Vaccination, there should be some variables to consider:
 - Vaccination Date
 - Certificate Valid From = Vaccination Date + X Days (how many days it takes to become immune)
 - Certificate Expiry Date = Vaccination Date + Y Days (Period when the QR Code can be considered as valid)
 
For Test
 - Valid From =  Test Sample Taken Date/Time
 - Valid Until = Valid From + X Hours (in Cyprus this is 72 hours)
 - Positive vs Negative = If a person has Covid, we should NOT allow to generate the Certificate.
 - If for some reason the Certificate is generated for a Covid Positive result, the expiry date must be set to the current date/time, as to have it expired immediately.

For Recovery
 - Valid From = CertificateValidFrom field from the form
 - Valid Until  = CertificateValidTo field from the form.
 - Parameter for Valid Days should be defined for validation that will ensure that the ValidUntil does not exceed ValidFrom + Parameter Valid Days.

**Comment by ggrund-tsi** [comment]
Hi psavva,

for Vaccination and Test the dates were set in backend.
So maybe it is possible to adjust your Cyprus issuance service regarding that?

Best regards, Gordon

**Comment by psavva** [comment]
Hi @ggrund-tsi, 

The Vaccination and Test Dates are set in the FrontEnd.
Only 2 Requests are set to the backend.  First to get the DGCI (No Dates)
Second is to supply the Hash (No Dates either here)

All Dates are defined in the FrontEnd when using the DGCA-Issuance-Web.

Please see the code here: 
https://github.com/eu-digital-green-certificates/dgca-issuance-web/blob/d709ee3a0b7e3c2282c23ddc5c3a2bbde0cdaa91/src/misc/edgcProcessor.tsx#L46

`
const expiredSeconds = 60 * 60 * 24 * 364;
`
```
const encodeCBOR = (certData: any, certMetaData: CertificateMetaData): Buffer => {

    const cborMap = new cbor.Map();
    const issuedAtSec = Date.now() / 1000 | 0;

    // expiration
    cborMap.set((4 as number), issuedAtSec + expiredSeconds);
    // issued at
    cborMap.set((6 as number), issuedAtSec);
    // issuer country code
    cborMap.set((1 as number), certMetaData.countryCode);
    const v1 = new cbor.Map();
    v1.set((1 as number), certData)
    cborMap.set((-260 as number), v1);

    return cbor.encode(cborMap);
}

```

**Comment by psavva** [comment]
@ggrund-tsi  Please also see related: https://github.com/eu-digital-green-certificates/dgca-issuance-service/issues/73

**Comment by ggrund-tsi** [comment]
Hi @psavva,

you are right. This fact was not present for me.

regards

**Comment by psavva** [comment]
@daniel-eder  I think this issue is critical and needs some attention how to proceed with some urgency.
Any member state that produces for example a Covid Test Certificate, will result in having a certificate valid for 1 year, when they may need to have it only valid for 3 days.
I can of course fix this for Cyprus, but I think this requires attention, and the dates expected is not what is coded here.

Same applies for the Recovery for the WEb and the Issuance Service.  Please see the linked issue .
https://github.com/eu-digital-green-certificates/dgca-issuance-service/issues/73

**Comment by daniel-eder** [comment]
@SchulzeStTSI can you comment on this?

**Comment by SchulzeStTSI** [comment]
@psavva please check out this branch before we merge it https://github.com/eu-digital-green-certificates/dgca-issuance-web/tree/fix/cert-expiration

**Comment by psavva** [comment]
This is definitely in the right direction.
I would not hard code the periods, as each country has the option to configure the validity period.

Tests are still valid for a full year.

This PR will fix the Recovery Cert with the limitation of the duration.

**Comment by ggrund-tsi** [comment]
@psavva now issuance service provide 3 days expiration for test certificate

**Comment by psavva** [comment]
Hi @ggrund-tsi

The expiration for the Test and Vaccination is set on the web when issuing a cert using this interface.

The issuance service does not control the issued and expiration dates at all.

The expiration is now set using your function 
const getExpiration = (certData: EUDGC, certMetaData: CertificateMetaData) =&gt; {    let result = certMetaData.expired;
    if (certData &amp;&amp; certData.r &amp;&amp; certData.r[0]) {        result = new Date(certData.r[0].du).getTime() / 1000 | 0;    }
    return result;}<br class="Apple-interchange-newline">

However, it's only handling the expiration of the recovery.  It must handle for all 3 types of certs.

ie: r,t,v collections

**Comment by psavva** [comment]
@ggrund-tsi   @SchulzeStTSI Do you agree with my analysis here? 
How shall we proceed?

**Comment by ggrund-tsi** [comment]
Hi @psavva,

for me this issue is finished. I don't understand what you mean.
Maybe I miss something?

I try to show my point of view.

recovery case:
only in this case you have the possibility to have influence on expiration in frontend.
The values 'Certificate Valid From - To*' calculate the expiration (now until 'Valid To').
This calculated value is entered in cose header.

vaccination and test case:
for these cases in frontend is no datepicker to choose expiration date. (no need for fulfill JSON Schema)
But for cose header you need an expiration date. This expirations are set in issuance service: line 51 in https://github.com/eu-digital-green-certificates/dgca-issuance-service/blob/main/src/main/resources/application.yml.
You get this expiration value as response from '/dgca-issuance-service/dgci/issue'.

I'm open for any other proposals and will discuss those things with achitecture lead but for the moment I see no real issue.

best regards, Gordon

**Comment by psavva** [comment]
Hi @ggrund-tsi 

I might have a misunderstand here, but I don't believe the endpoint 'dgca-issuance-service/dgci/issue' for Vaccination and Recovery are using the overload which accepts the data as per hcert-schema, but it's using the overloads as such:

1) return api.post('/dgca-issuance-service/dgci/issue', certInit)
where certInit only contains one value of
enum CertType {    Vaccination = 'Vaccination',    Recovery = 'Recovery',    Test = 'Test'}

2) Generate the QR code internal to the WEB implementation via 
createCertificateQRData(edgcPayload, certMetaData,                (hash) 
 And last, call the signerCall function which only accepts there Id and hash in order to get the TAN.

const signerCall = (id: string, hash: string): Promise&lt;SigResponse&gt; =&gt; {    return api.put('/dgca-issuance-service/dgci/issue/' + id, { hash: hash })        .then(res =&gt; {            const sigResponse: SigResponse = res.data;            return sigResponse;        });}<br class="Apple-interchange-newline">

At no point in the Web Issuance is the api which creates the QR Code from the Issuance Service.

Please let me know if I've missed something here.

Best Regards
Panayiotis Savva

**Comment by ggrund-tsi** [comment]
> 
> At no point in the Web Issuance code is it calling the api which creates the QR Code from the DGCA-Issuance-Service.
> 
> Please let me know if I've missed something here.
> 

Hi @psavva,

for dataprivacy reasons (in germany) almost the complete QR-Code will be created in frontend. --> No personal data leaves frontend until wallet or verifier scan.
Only hash signing will be made by issuance-service.
Because of the need of other/backend implementations issuance-service also provides the creating functionality.

I hope this will clarify the issue and maybe we will hear us later.

best regards, Gordon

**Comment by psavva** [comment]
Hi @ggrund-tsi 

We are on the same page here :)

But now you can see the implementation in the WEB Frontend is missing the expiry date handing for Vaccination and Tests?

https://github.com/eu-digital-green-certificates/dgca-issuance-web/blob/b543bc472f9651cc28c3bba1452d3e088ebfcf4f/src/misc/edgcProcessor.tsx#L64

```
const getExpiration = (certData: EUDGC, certMetaData: CertificateMetaData) =&gt; {    let result = certMetaData.expired;
    if (certData &amp;&amp; certData.r &amp;&amp; certData.r[0]) {        result = new Date(certData.r[0].du).getTime() / 1000 | 0;    }
    return result;}<br class="Apple-interchange-newline">
```

The above function must handle for **certData.v** and **certData.t**

**Comment by ggrund-tsi** [comment]
Hi @psavva ,

in first line of getExpiration method the default-expiration from issance service is set.
`let result = certMetaData.expired;`

certMetaData is the response from `/dgca-issuance-service/dgci/issue` - I mentioned.

`getExpiration` Method will override the issuance-service expiration only for recovery case.

regards.

**Comment by ggrund-tsi** [comment]
> 
> The above function must handle for **certData.v** and **certData.t**

it's handled implicite in `/dgca-issuance-service/dgci/issue` - you mentioned

> return api.post('/dgca-issuance-service/dgci/issue', certInit)
> where certInit only contains one value of
> enum CertType { Vaccination = 'Vaccination', Recovery = 'Recovery', Test = 'Test'}

**Comment by psavva** [comment]
Let's discuss in our call in 20  mins with @SchulzeStTSI

**Comment by ggrund-tsi** [comment]
please see possible fix:
`https://github.com/eu-digital-green-certificates/dgca-issuance-web/tree/fix/expiration-for-vac-and-tst`

**Comment by lexin10** [comment]
This branch https://github.com/eu-digital-green-certificates/dgca-issuance-web/tree/fix/expiration-for-vac-and-tst
will be merge to main?

**Comment by ggrund-tsi** [comment]
Hi @lexin10,

we've needed to adjust issuance service before.
Now it is able to merge (#93).

regards, Gordon
